### ISSUE TITLE
Extension error when opening solution file directly

### ISSUE THREAD

**Issue by jcramer** [Therena/ConEmuIntegration#7]
I have VS2017 installed and conemu fails to load whenever I try to open a certain solution from the solution file directly.  If I start VS2017 without a solution loaded conemu integration works fine, and I can then open a solution from the VS2017 UI without issue.  The following error message are presented when opening solution file directly:

![image](https://cloud.githubusercontent.com/assets/988195/23795465/dd7733b2-0563-11e7-952f-7b07bf65735f.png)

![image](https://cloud.githubusercontent.com/assets/988195/23795588/6438c604-0564-11e7-87b1-5365859225e5.png)

For whatever reason this behavior doesn't occur with all solution files, but it does with primary working solution... of course. :-)

**Comment by Therena** [comment]
Hi,

thanks for reporting this issue.
Unfortunately I'm unable to reproduce this on my system.

Anyway I added some possible fixes in the newest release (2.0.0.11).
Would be nice if you could check if it solves your problem and tell me the results.

> For whatever reason this behavior doesn't occur with all solution files

In case it isn't solved already, it would be helpful if you could provide me a solution file with which this issue is reproducible.

Regards,
Therena

**Comment by rrajewski** [comment]
I'm not OP, but the new release fixed the issue for me. I was getting the error whenever I opened a solution that had the ConEmu window pinned and visible the last time I closed it. 

Thanks for making this extension, it is awesome!!!

**Comment by jcramer** [comment]
Thank you! Works great!
