### ISSUE TITLE
Powershell support

### ISSUE THREAD

**Issue by Leon99** [Therena/ConEmuIntegration#8]
Powershell is now the default command processor. Please add Powershell support for the context menu commands.

**Comment by Therena** [comment]
@Leon99 Please go to configuration and set the default task to "powershell". So that the integration knows you are using something else than cmd. It should then use the powershell set of commands.
![image](https://cloud.githubusercontent.com/assets/18515874/24281841/fa15d322-105b-11e7-8aaa-7ab43eb1e11f.png)
Please let me know if this solves your issue. Thanks.

**Comment by Therena** [comment]
I assume it worked for you. I will close the issue because of no new message about this issue.
